"""
Generate a pitched-blade turbine (PBT) impeller STL for marblesThermal.

Geometry reference: Reference Solver CFD "Modeling Chemical Reactions" tutorial
  (reference solver documentation)
  - Tank: 0.3 m tall x 0.3 m diameter, dx = 2.344e-3 m  (128x128 cells)
  - Impeller: 0.125 m diameter, 4-blade 45-degree pitched blade turbine (PBT-4)

The STL is centred at the origin; eb2.stl_center in the inp file moves it to the
body centre (64, 64, -23 in lattice-cell units).

Design parameters (in lattice-cell units, dx = 2.344e-3 m):
  blade_outer_radius = 26.7  cells  (= D_imp/2 = 0.0625 m)
  blade_inner_radius =  8.0  cells  (hub surface, ~ D_imp/6.7)
  hub_radius         =  8.0  cells  (solid shaft hub)
  hub_height         = 12.0  cells  (= 0.028 m)
  blade_width        = 12.0  cells  (= 0.028 m, the axial extent before pitching)
  blade_thickness    =  2.5  cells  (= 0.0059 m, thin flat plate)
  pitch_angle        = 45 degrees   (standard PBT, generates downward axial flow)
  num_blades         = 4

Six-face closed box per blade (12 triangles) + closed cylinder hub (2*num_seg + 2 caps).
All normals point outward from the solid.  The blade boxes slightly overlap the hub
cylinder so there is no gap; AMReX EB computes the union automatically.
"""

import numpy as np
import struct


# ---------------------------------------------------------------------------
# STL writer
# ---------------------------------------------------------------------------

def write_stl(filename, vertices, faces):
    """Write binary STL.  Normals are computed from CCW vertex winding."""
    normals = []
    for face in faces:
        v1 = np.array(vertices[face[0]])
        v2 = np.array(vertices[face[1]])
        v3 = np.array(vertices[face[2]])
        n = np.cross(v2 - v1, v3 - v1)
        ln = np.linalg.norm(n)
        if ln > 0:
            n /= ln
        normals.append(n)

    with open(filename, 'wb') as f:
        header = b'Pitched blade turbine impeller - generated by generate_pitched_impeller_stl.py'
        f.write(header + b'\x00' * (80 - len(header)))
        f.write(struct.pack('<I', len(faces)))
        for i, face in enumerate(faces):
            f.write(struct.pack('<3f', *normals[i]))
            for vi in face:
                f.write(struct.pack('<3f', *vertices[vi]))
            f.write(struct.pack('<H', 0))


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------

def add_quad(verts, facs, p1, p2, p3, p4):
    """Split a planar quad into two triangles (CCW winding from outside)."""
    i = len(verts)
    verts += [p1, p2, p3, p4]
    facs.append((i,   i+1, i+2))
    facs.append((i,   i+2, i+3))


# ---------------------------------------------------------------------------
# Blade generator  (single closed rectangular box, pitched and rotated)
# ---------------------------------------------------------------------------

def generate_blade(r_inner, r_outer, blade_width, blade_thickness,
                   pitch_deg, phi_deg, cx, cy, cz):
    """
    Return (vertices, faces) for one pitched blade, placed at azimuthal
    angle phi_deg around the z-axis.

    Local frame (before any rotation, blade extending in +x direction):
      x  : radial,   r_inner -> r_outer
      y  : tangential thickness,  -t/2 -> +t/2
      z  : axial blade width (to be pitched),  -w/2 -> +w/2

    Pitch rotation R_x(pitch_deg) rotates about the radial (x) axis:
      pitch_deg =  0  -> blade horizontal (lying flat)
      pitch_deg = 45  -> standard PBT geometry, pumps fluid axially
      pitch_deg = 90  -> blade vertical (like a flat Rushton blade)

    Positive pitch tilts the leading edge (+z) upward and the trailing edge
    (+y side) downward, producing downward axial flow for CCW rotation.

    Winding: CCW when viewed from outside (outward normals), verified below.
    """
    pitch = np.radians(pitch_deg)
    phi   = np.radians(phi_deg)
    t = blade_thickness / 2.0
    w = blade_width     / 2.0

    # 8 corners in local unrotated frame
    local = np.array([
        [r_inner, -t, -w],  # 0: inner, leading-face,  bottom
        [r_outer, -t, -w],  # 1: outer, leading-face,  bottom
        [r_outer,  t, -w],  # 2: outer, trailing-face, bottom
        [r_inner,  t, -w],  # 3: inner, trailing-face, bottom
        [r_inner, -t,  w],  # 4: inner, leading-face,  top
        [r_outer, -t,  w],  # 5: outer, leading-face,  top
        [r_outer,  t,  w],  # 6: outer, trailing-face, top
        [r_inner,  t,  w],  # 7: inner, trailing-face, top
    ])

    # Pitch: rotate about x-axis (radial direction)
    cp, sp = np.cos(pitch), np.sin(pitch)
    Rx = np.array([[ 1,  0,   0],
                   [ 0, cp, -sp],
                   [ 0, sp,  cp]])

    # Azimuthal placement: rotate about z-axis
    cf, sf = np.cos(phi), np.sin(phi)
    Rz = np.array([[cf, -sf, 0],
                   [sf,  cf, 0],
                   [ 0,   0, 1]])

    # Combined rotation then translate to impeller centre
    R = Rz @ Rx
    world = (R @ local.T).T + np.array([cx, cy, cz])
    c = [tuple(v) for v in world]

    verts, facs = [], []

    # 6 faces, outward normals verified by cross-product:
    #
    # BOTTOM  face  (outward = -z_local):  winding c[0],c[3],c[2],c[1]
    #   v1 = c[3]-c[0] = (0,2t,0), v2 = c[2]-c[0] = (r_len,2t,0)
    #   cross → (0, 0, -2t*r_len)  →  -z  ✓
    add_quad(verts, facs, c[0], c[3], c[2], c[1])

    # TOP     face  (outward = +z_local):  winding c[4],c[5],c[6],c[7]
    #   v1 = c[5]-c[4] = (r_len,0,0), v2 = c[6]-c[4] = (r_len,2t,0)
    #   cross → (0, 0, 2t*r_len)   →  +z  ✓
    add_quad(verts, facs, c[4], c[5], c[6], c[7])

    # LEADING face  (outward = -y_local):  winding c[0],c[1],c[5],c[4]
    #   v1 = c[1]-c[0] = (r_len,0,0), v2 = c[5]-c[0] = (r_len,0,2w)
    #   cross → (0, -2w*r_len, 0)  →  -y  ✓
    add_quad(verts, facs, c[0], c[1], c[5], c[4])

    # TRAILING face (outward = +y_local):  winding c[2],c[3],c[7],c[6]
    #   v1 = c[3]-c[2] = (-r_len,0,0), v2 = c[7]-c[2] = (-r_len,0,2w)
    #   cross → (0, 2w*r_len, 0)  →  +y  ✓
    add_quad(verts, facs, c[2], c[3], c[7], c[6])

    # INNER   face  (outward = -x_local):  winding c[0],c[4],c[7],c[3]
    #   v1 = c[4]-c[0] = (0,0,2w), v2 = c[7]-c[0] = (0,2t,2w)
    #   cross → (-4tw, 0, 0)       →  -x  ✓
    add_quad(verts, facs, c[0], c[4], c[7], c[3])

    # OUTER   face  (outward = +x_local):  winding c[1],c[2],c[6],c[5]
    #   v1 = c[2]-c[1] = (0,2t,0),  v2 = c[6]-c[1] = (0,2t,2w)
    #   cross → (4tw, 0, 0)         →  +x  ✓
    add_quad(verts, facs, c[1], c[2], c[6], c[5])

    return verts, facs


# ---------------------------------------------------------------------------
# Hub cylinder generator
# ---------------------------------------------------------------------------

def generate_hub_cylinder(cx, cy, cz, radius, height, num_seg=64):
    """
    Return (vertices, faces) for a closed cylinder centred at (cx,cy,cz).
    Height is the total axial extent (symmetric about cz).
    Outward normals.

    Side-face winding: add_quad(BL, BR, TR, TL) where BL/BR/TR/TL are
    bottom-left, bottom-right, top-right, top-left w.r.t. the arc segment.
    Normal of first triangle: v1 = BR-BL, v2 = TR-BL
        cross(v1,v2) ≈ (+y2-y1)*dz, -(x2-x1)*dz, 0) → radially outward ✓
    """
    verts, facs = [], []
    z0 = cz - height / 2.0
    z1 = cz + height / 2.0

    angs = [2.0 * np.pi * i / num_seg for i in range(num_seg)]

    # Side faces
    for i in range(num_seg):
        a1 = angs[i]
        a2 = angs[(i + 1) % num_seg]
        x1, y1 = cx + radius * np.cos(a1), cy + radius * np.sin(a1)
        x2, y2 = cx + radius * np.cos(a2), cy + radius * np.sin(a2)
        bl = (x1, y1, z0)
        br = (x2, y2, z0)
        tr = (x2, y2, z1)
        tl = (x1, y1, z1)
        add_quad(verts, facs, bl, br, tr, tl)

    # Top cap: outward normal = +z  →  CCW when viewed from above
    tc_idx = len(verts)
    verts.append((cx, cy, z1))
    for i in range(num_seg):
        a1 = angs[i]
        a2 = angs[(i + 1) % num_seg]
        p1 = (cx + radius * np.cos(a1), cy + radius * np.sin(a1), z1)
        p2 = (cx + radius * np.cos(a2), cy + radius * np.sin(a2), z1)
        p1i = len(verts); verts.append(p1)
        p2i = len(verts); verts.append(p2)
        # centre, p1, p2 : cross(p1-centre, p2-centre) = (0,0,r²*sin(da)) → +z ✓
        facs.append((tc_idx, p1i, p2i))

    # Bottom cap: outward normal = -z  →  CCW when viewed from below (reverse p1/p2)
    bc_idx = len(verts)
    verts.append((cx, cy, z0))
    for i in range(num_seg):
        a1 = angs[i]
        a2 = angs[(i + 1) % num_seg]
        p1 = (cx + radius * np.cos(a1), cy + radius * np.sin(a1), z0)
        p2 = (cx + radius * np.cos(a2), cy + radius * np.sin(a2), z0)
        p1i = len(verts); verts.append(p1)
        p2i = len(verts); verts.append(p2)
        # Reverse order: cross(p2-centre, p1-centre) → -z ✓
        facs.append((bc_idx, p2i, p1i))

    return verts, facs


# ---------------------------------------------------------------------------
# Top-level assembly
# ---------------------------------------------------------------------------

def generate_pitched_blade_impeller(
        blade_outer_radius = 26.7,
        blade_inner_radius =  8.0,
        blade_width        = 12.0,
        blade_thickness    =  2.5,
        hub_radius         =  8.0,
        hub_height         = 12.0,
        pitch_angle        = 45.0,
        num_blades         = 4,
        center             = (0.0, 0.0, 0.0),
        hub_seg            = 64,
    ):
    """
    Assemble hub + blades into a single STL vertex/face list.

    The blade inner radius equals the hub outer radius.  The blade boxes share
    the hub surface so there is no gap; the tiny radial overlap (0.1 cell) is
    intentional to guarantee continuity when AMReX evaluates the solid region.
    """
    cx, cy, cz = center
    all_verts = []
    all_faces = []

    # ---- hub cylinder ----
    hverts, hfacs = generate_hub_cylinder(cx, cy, cz, hub_radius, hub_height,
                                          num_seg=hub_seg)
    offset = len(all_verts)
    all_verts += hverts
    all_faces += [(f[0]+offset, f[1]+offset, f[2]+offset) for f in hfacs]

    # ---- blades ----
    for k in range(num_blades):
        phi = 360.0 * k / num_blades          # degrees, equally spaced
        # Overlap the hub by 0.1 cell on the inner edge so there is no gap
        r_in = blade_inner_radius - 0.1
        bverts, bfacs = generate_blade(
            r_in, blade_outer_radius,
            blade_width, blade_thickness,
            pitch_angle, phi,
            cx, cy, cz
        )
        offset = len(all_verts)
        all_verts += bverts
        all_faces += [(f[0]+offset, f[1]+offset, f[2]+offset) for f in bfacs]

    return all_verts, all_faces


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    import os

    # ---- parameters (lattice-cell units; dx = 2.344e-3 m) ----
    params = dict(
        blade_outer_radius = 26.7,   # cells  D_imp/2 = 0.0625 m
        blade_inner_radius =  8.0,   # cells  ~D_imp/6.7
        blade_width        = 12.0,   # cells  0.028 m  (axial extent before pitching)
        blade_thickness    =  2.5,   # cells  0.0059 m (thin plate)
        hub_radius         =  8.0,   # cells  shared with blade_inner_radius
        hub_height         = 12.0,   # cells  0.028 m  (taller than pitched blade span)
        pitch_angle        = 45.0,   # degrees
        num_blades         = 4,
        center             = (0.0, 0.0, 0.0),
        hub_seg            = 64,     # cylinder approximation segments
    )

    verts, faces = generate_pitched_blade_impeller(**params)

    outdir = os.path.dirname(os.path.abspath(__file__))
    outfile = os.path.join(outdir, 'pitched_impeller.stl')
    write_stl(outfile, verts, faces)

    # ---- geometry report ----
    va = np.array(verts)
    print(f"Output: {outfile}")
    print(f"Triangles : {len(faces)}")
    print(f"Vertices  : {len(verts)}")
    print(f"X range   : [{va[:,0].min():.2f}, {va[:,0].max():.2f}] cells")
    print(f"Y range   : [{va[:,1].min():.2f}, {va[:,1].max():.2f}] cells")
    print(f"Z range   : [{va[:,2].min():.2f}, {va[:,2].max():.2f}] cells")
    r_max = np.max(np.sqrt(va[:,0]**2 + va[:,1]**2))
    print(f"Max radial extent : {r_max:.2f} cells")
    print()
    print("To use in stirred_tank_reacting.inp:")
    print("  eb2.stl_file   = \"Build/pitched_impeller.stl\"")
    print("  eb2.stl_center = 64.0 64.0 -23.0")
    print("  (body.center and body.angular_velocity unchanged)")
